### ISSUE TITLE
When initialize ons-tab occur an error:"icon.attributeChangedCallback is not a function"

### ISSUE THREAD

**Issue by Henry0126** [OnsenUI/OnsenUI#2247]
[Core]
    onsenui 2.7.2

[Framework]
    angular1 1.5.9

[Framework binding]
    angular-onsenui 2.7.2

[Additional libraries]
    jQuery 3.1.1

![image](https://user-images.githubusercontent.com/25029204/32712686-89d9a4d6-c80b-11e7-8b0d-f872af3b9110.png)

Recently, I try to upgrade onsenui from 2.1.0. to 2.7.2 and this problem happens , the error pirnt as "Uncaught (in promise) TypeError: icon.attributeChangedCallback is not a function", I dont know  how to solve it.

**Comment by asial-matagawa** [comment]
@Henry0126 
Thank you for reporting.
Could you provide some code to reproduce the problem?

**Comment by Henry0126** [comment]
![image](https://user-images.githubusercontent.com/25029204/32713124-6d436986-c80d-11e7-97a5-57a0328144eb.png)
these are the main code related to the ons-tab in my project, it works well in onsenui 2.4.0,but I changed the onsenui.min.js and angular-onsenui.min.js and other css resources,the error happens.

**Comment by frandiox** [comment]
@Henry0126 Any chance that you can reproduce this issue [here](http://tutorial.onsen.io/?framework=angular1&category=reference&module=tabbar) and hit `Report an issue`? Otherwise, it's going to be hard to reproduce...
